package domain

import (
	"errors"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/golang-jwt/jwt/v5"
	"github.com/google/uuid"
)

type TokenType string

const (
	TypeAccessToken  TokenType = "access_token"
	TypeRefreshToken TokenType = "refresh_token"
)

type CustomClaims struct {
	jwt.RegisteredClaims
	TokenType         TokenType `json:"token_type"`
	Roles             RoleMap   `json:"roles"`
	SessionID         string    `json:"session_id"`
	AuthProvider      string    `json:"auth_provider"`
	OAuthRefreshToken string    `json:"oauth_refresh_token,omitempty"`
	OAuthProvider     string    `json:"oauth_provider,omitempty"`
}

func (c CustomClaims) GetUserID() string {
	return c.Subject
}

func (c CustomClaims) GetRoles() RoleMap {
	return c.Roles
}

func (c CustomClaims) GetAuthProvider() string {
	return c.AuthProvider
}

func (c CustomClaims) GetSessionID() string {
	return c.SessionID
}

// GetAudience returns the audience of the token (ie. tenant IDs)
func (c CustomClaims) GetAudience() (jwt.ClaimStrings, error) {
	return c.Audience, nil
}

func (c CustomClaims) GetUserContextData() *UserContextData {
	return &UserContextData{
		UserID:       c.Subject,
		Roles:        c.Roles,
		AuthProvider: c.AuthProvider,
		SessionID:    c.SessionID,
	}
}

// TokenManager handles JWT operations using Ed25519 (EdDSA) signing.
type TokenManager struct {
	keyManager        *KeyManager   // keyManager provides Ed25519 signing/verification keys
	issuer            string        // issuer is the name of the service that is issuing the token
	accessExpiration  time.Duration // expiration is the duration of tokens generated by this manager
	refreshExpiration time.Duration // expiration is the duration of tokens generated by this manager
}

// NewTokenManager creates a new JWTManager that signs tokens with Ed25519.
func NewTokenManager(keyManager *KeyManager, issuer string, accessExpiration, refreshExpiration time.Duration) *TokenManager {
	return &TokenManager{
		keyManager:        keyManager,
		issuer:            issuer,
		accessExpiration:  accessExpiration,
		refreshExpiration: refreshExpiration,
	}
}

// TokenPair represents a pair of access and refresh tokens.
type TokenPair struct {
	AccessToken  AccessToken  `json:"access_token"`
	RefreshToken RefreshToken `json:"refresh_token"`
}

type AccessToken string
type RefreshToken string

// GenerateTokenPair creates a new JWT token and refresh token
// if oauthToken is provided, it will be included in the refresh token to be used for oauth token refresh
func (m *TokenManager) GenerateTokenPair(userID string, sessionID string, authProvider AuthProvider, roles RoleMap, oauthToken *OAuthToken) (*TokenPair, error) {
	tenantAudience := roles.GetTenantIDsAsStrings()

	now := time.Now()
	claims := CustomClaims{
		RegisteredClaims: jwt.RegisteredClaims{
			ID:        uuid.New().String(),
			Issuer:    m.issuer,       // issuer is the domain name of the service that is issuing the token
			Subject:   userID,         // subject is the user ID
			Audience:  tenantAudience, // audience is the list of tenant IDs this user has access to
			ExpiresAt: jwt.NewNumericDate(now.Add(m.accessExpiration)),
			IssuedAt:  jwt.NewNumericDate(now),
			NotBefore: jwt.NewNumericDate(now),
		},
		TokenType:    TypeAccessToken,
		Roles:        roles,
		SessionID:    sessionID,
		AuthProvider: string(authProvider),
	}
	if oauthToken != nil {
		claims.OAuthRefreshToken = oauthToken.RefreshToken
		claims.OAuthProvider = oauthToken.Provider
	}

	activeKey := m.keyManager.ActiveKey()
	token := jwt.NewWithClaims(jwt.SigningMethodEdDSA, claims)
	token.Header["kid"] = activeKey.KID
	accessToken, err := token.SignedString(activeKey.PrivateKey)
	if err != nil {
		return nil, err
	}

	refreshToken, err := m.makeRefreshToken(userID, sessionID, claims.ID, authProvider, oauthToken)
	if err != nil {
		return nil, err
	}

	return &TokenPair{
		AccessToken:  AccessToken(accessToken),
		RefreshToken: RefreshToken(refreshToken),
	}, nil
}

// ValidateToken validates the JWT token using Ed25519 public key lookup by KID.
func (m *TokenManager) ValidateToken(tokenString string) (*CustomClaims, error) {
	token, err := jwt.ParseWithClaims(tokenString, &CustomClaims{}, func(token *jwt.Token) (any, error) {
		if token.Method.Alg() != jwt.SigningMethodEdDSA.Alg() {
			return nil, fmt.Errorf("unexpected signing method: %s", token.Method.Alg())
		}

		kid, ok := token.Header["kid"].(string)
		if !ok || kid == "" {
			return nil, errors.New("missing kid in token header")
		}

		pubKey, err := m.keyManager.FindPublicKey(kid)
		if err != nil {
			return nil, fmt.Errorf("unknown kid: %w", err)
		}

		return pubKey, nil
	})

	if err != nil {
		return nil, err
	}

	if claims, ok := token.Claims.(*CustomClaims); ok && token.Valid {
		if claims.ExpiresAt.Before(time.Now()) {
			return nil, ErrTokenExpired
		}
		return claims, nil
	}

	return nil, errors.New("invalid token")
}

// RefreshToken generates a new token with a new expiration time
// if oauthToken is provided, it will be included in the refresh token to be used for oauth token refresh
func (m *TokenManager) RefreshToken(tokenString string, oauthToken *OAuthToken) (*TokenPair, error) {
	claims, err := m.ValidateToken(tokenString)
	if err != nil {
		return nil, err
	}

	if claims.TokenType != TypeRefreshToken {
		return nil, errors.New("invalid token type")
	}

	claims.ExpiresAt = jwt.NewNumericDate(time.Now().Add(m.refreshExpiration))
	claims.IssuedAt = jwt.NewNumericDate(time.Now())
	claims.NotBefore = jwt.NewNumericDate(time.Now())

	activeKey := m.keyManager.ActiveKey()
	token := jwt.NewWithClaims(jwt.SigningMethodEdDSA, claims)
	token.Header["kid"] = activeKey.KID
	accessToken, err := token.SignedString(activeKey.PrivateKey)
	if err != nil {
		return nil, err
	}

	refreshToken, err := m.makeRefreshToken(claims.Subject, claims.SessionID, claims.ID, AuthProvider(claims.AuthProvider), oauthToken)
	if err != nil {
		return nil, err
	}

	return &TokenPair{
		AccessToken:  AccessToken(accessToken),
		RefreshToken: RefreshToken(refreshToken),
	}, nil
}

// makeRefreshToken creates a refresh token.
// If oauthToken is provided, it includes only the OAuth refresh token in the claims.
func (m *TokenManager) makeRefreshToken(userID, sessionID, jti string, authProvider AuthProvider, oauthToken *OAuthToken) (RefreshToken, error) {
	claims := CustomClaims{
		RegisteredClaims: jwt.RegisteredClaims{
			ID:        jti,
			Issuer:    m.issuer,
			Subject:   userID,
			ExpiresAt: jwt.NewNumericDate(time.Now().Add(m.refreshExpiration)),
			IssuedAt:  jwt.NewNumericDate(time.Now()),
			NotBefore: jwt.NewNumericDate(time.Now()),
		},
		TokenType:    TypeRefreshToken,
		SessionID:    sessionID,
		AuthProvider: string(authProvider),
	}
	// Optionally include only the OAuth refresh token if provided.
	if oauthToken != nil {
		claims.OAuthRefreshToken = oauthToken.RefreshToken
		claims.OAuthProvider = oauthToken.Provider
		// You can also include any other minimal fields you need.
	}

	activeKey := m.keyManager.ActiveKey()
	token := jwt.NewWithClaims(jwt.SigningMethodEdDSA, claims)
	token.Header["kid"] = activeKey.KID
	refreshToken, err := token.SignedString(activeKey.PrivateKey)
	if err != nil {
		return "", err
	}

	return RefreshToken(refreshToken), nil
}

// ExtractToken retrieves the access token from the request's Authorization header or cookies.
func ExtractTokenFromHeader(r *http.Request) (string, error) {
	var token string
	authHeader := r.Header.Get("Authorization")
	if authHeader != "" {
		parts := strings.SplitN(authHeader, " ", 2)
		if len(parts) == 2 && strings.EqualFold(parts[0], "Bearer") {
			token = parts[1]
		}
	}

	return token, nil
}

func (m *TokenManager) ParseRefreshToken(refreshToken string) (*CustomClaims, error) {
	token, err := jwt.ParseWithClaims(refreshToken, &CustomClaims{}, func(token *jwt.Token) (any, error) {
		if token.Method.Alg() != jwt.SigningMethodEdDSA.Alg() {
			return nil, fmt.Errorf("unexpected signing method: %s", token.Method.Alg())
		}

		kid, ok := token.Header["kid"].(string)
		if !ok || kid == "" {
			return nil, errors.New("missing kid in token header")
		}

		pubKey, err := m.keyManager.FindPublicKey(kid)
		if err != nil {
			return nil, fmt.Errorf("unknown kid: %w", err)
		}

		return pubKey, nil
	})
	if err != nil {
		return nil, err
	}

	if claims, ok := token.Claims.(*CustomClaims); ok && token.Valid {
		return claims, nil
	}

	return nil, errors.New("invalid token")
}

type OAuthToken struct {
	AccessToken  string
	RefreshToken string
	Expiry       time.Time
	Provider     string
}
