// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: schema_registry.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SchemaRegistry_CreateSchema_FullMethodName       = "/schema.SchemaRegistry/CreateSchema"
	SchemaRegistry_GetSchema_FullMethodName          = "/schema.SchemaRegistry/GetSchema"
	SchemaRegistry_UpdateSchema_FullMethodName       = "/schema.SchemaRegistry/UpdateSchema"
	SchemaRegistry_DeleteSchema_FullMethodName       = "/schema.SchemaRegistry/DeleteSchema"
	SchemaRegistry_ListSchemas_FullMethodName        = "/schema.SchemaRegistry/ListSchemas"
	SchemaRegistry_CreateBundle_FullMethodName       = "/schema.SchemaRegistry/CreateBundle"
	SchemaRegistry_GetBundle_FullMethodName          = "/schema.SchemaRegistry/GetBundle"
	SchemaRegistry_ListBundles_FullMethodName        = "/schema.SchemaRegistry/ListBundles"
	SchemaRegistry_RegisterService_FullMethodName    = "/schema.SchemaRegistry/RegisterService"
	SchemaRegistry_DeregisterService_FullMethodName  = "/schema.SchemaRegistry/DeregisterService"
	SchemaRegistry_ServiceHeartbeat_FullMethodName   = "/schema.SchemaRegistry/ServiceHeartbeat"
	SchemaRegistry_ListServices_FullMethodName       = "/schema.SchemaRegistry/ListServices"
	SchemaRegistry_CheckCompatibility_FullMethodName = "/schema.SchemaRegistry/CheckCompatibility"
	SchemaRegistry_CompileProto_FullMethodName       = "/schema.SchemaRegistry/CompileProto"
	SchemaRegistry_WatchSchemas_FullMethodName       = "/schema.SchemaRegistry/WatchSchemas"
	SchemaRegistry_WatchServices_FullMethodName      = "/schema.SchemaRegistry/WatchServices"
)

// SchemaRegistryClient is the client API for SchemaRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchemaRegistryClient interface {
	// Schema Management
	CreateSchema(ctx context.Context, in *CreateSchemaRequest, opts ...grpc.CallOption) (*SchemaResponse, error)
	GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*SchemaResponse, error)
	UpdateSchema(ctx context.Context, in *UpdateSchemaRequest, opts ...grpc.CallOption) (*SchemaResponse, error)
	DeleteSchema(ctx context.Context, in *DeleteSchemaRequest, opts ...grpc.CallOption) (*DeleteSchemaResponse, error)
	ListSchemas(ctx context.Context, in *ListSchemasRequest, opts ...grpc.CallOption) (*ListSchemasResponse, error)
	// Bundle Management
	CreateBundle(ctx context.Context, in *CreateBundleRequest, opts ...grpc.CallOption) (*BundleResponse, error)
	GetBundle(ctx context.Context, in *GetBundleRequest, opts ...grpc.CallOption) (*BundleResponse, error)
	ListBundles(ctx context.Context, in *ListBundlesRequest, opts ...grpc.CallOption) (*ListBundlesResponse, error)
	// Service Registration
	RegisterService(ctx context.Context, in *RegisterServiceRequest, opts ...grpc.CallOption) (*RegisterServiceResponse, error)
	DeregisterService(ctx context.Context, in *DeregisterServiceRequest, opts ...grpc.CallOption) (*DeregisterServiceResponse, error)
	ServiceHeartbeat(ctx context.Context, in *ServiceHeartbeatRequest, opts ...grpc.CallOption) (*ServiceHeartbeatResponse, error)
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	// Compatibility Testing
	CheckCompatibility(ctx context.Context, in *CheckCompatibilityRequest, opts ...grpc.CallOption) (*CheckCompatibilityResponse, error)
	// Proto Compilation
	CompileProto(ctx context.Context, in *CompileProtoRequest, opts ...grpc.CallOption) (*CompileProtoResponse, error)
	// Watch for changes
	WatchSchemas(ctx context.Context, in *WatchSchemasRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SchemaEvent], error)
	WatchServices(ctx context.Context, in *WatchServicesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceEvent], error)
}

type schemaRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewSchemaRegistryClient(cc grpc.ClientConnInterface) SchemaRegistryClient {
	return &schemaRegistryClient{cc}
}

func (c *schemaRegistryClient) CreateSchema(ctx context.Context, in *CreateSchemaRequest, opts ...grpc.CallOption) (*SchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchemaResponse)
	err := c.cc.Invoke(ctx, SchemaRegistry_CreateSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaRegistryClient) GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*SchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchemaResponse)
	err := c.cc.Invoke(ctx, SchemaRegistry_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaRegistryClient) UpdateSchema(ctx context.Context, in *UpdateSchemaRequest, opts ...grpc.CallOption) (*SchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchemaResponse)
	err := c.cc.Invoke(ctx, SchemaRegistry_UpdateSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaRegistryClient) DeleteSchema(ctx context.Context, in *DeleteSchemaRequest, opts ...grpc.CallOption) (*DeleteSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSchemaResponse)
	err := c.cc.Invoke(ctx, SchemaRegistry_DeleteSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaRegistryClient) ListSchemas(ctx context.Context, in *ListSchemasRequest, opts ...grpc.CallOption) (*ListSchemasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSchemasResponse)
	err := c.cc.Invoke(ctx, SchemaRegistry_ListSchemas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaRegistryClient) CreateBundle(ctx context.Context, in *CreateBundleRequest, opts ...grpc.CallOption) (*BundleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BundleResponse)
	err := c.cc.Invoke(ctx, SchemaRegistry_CreateBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaRegistryClient) GetBundle(ctx context.Context, in *GetBundleRequest, opts ...grpc.CallOption) (*BundleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BundleResponse)
	err := c.cc.Invoke(ctx, SchemaRegistry_GetBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaRegistryClient) ListBundles(ctx context.Context, in *ListBundlesRequest, opts ...grpc.CallOption) (*ListBundlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBundlesResponse)
	err := c.cc.Invoke(ctx, SchemaRegistry_ListBundles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaRegistryClient) RegisterService(ctx context.Context, in *RegisterServiceRequest, opts ...grpc.CallOption) (*RegisterServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterServiceResponse)
	err := c.cc.Invoke(ctx, SchemaRegistry_RegisterService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaRegistryClient) DeregisterService(ctx context.Context, in *DeregisterServiceRequest, opts ...grpc.CallOption) (*DeregisterServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeregisterServiceResponse)
	err := c.cc.Invoke(ctx, SchemaRegistry_DeregisterService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaRegistryClient) ServiceHeartbeat(ctx context.Context, in *ServiceHeartbeatRequest, opts ...grpc.CallOption) (*ServiceHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceHeartbeatResponse)
	err := c.cc.Invoke(ctx, SchemaRegistry_ServiceHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaRegistryClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, SchemaRegistry_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaRegistryClient) CheckCompatibility(ctx context.Context, in *CheckCompatibilityRequest, opts ...grpc.CallOption) (*CheckCompatibilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckCompatibilityResponse)
	err := c.cc.Invoke(ctx, SchemaRegistry_CheckCompatibility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaRegistryClient) CompileProto(ctx context.Context, in *CompileProtoRequest, opts ...grpc.CallOption) (*CompileProtoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompileProtoResponse)
	err := c.cc.Invoke(ctx, SchemaRegistry_CompileProto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaRegistryClient) WatchSchemas(ctx context.Context, in *WatchSchemasRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SchemaEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SchemaRegistry_ServiceDesc.Streams[0], SchemaRegistry_WatchSchemas_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchSchemasRequest, SchemaEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SchemaRegistry_WatchSchemasClient = grpc.ServerStreamingClient[SchemaEvent]

func (c *schemaRegistryClient) WatchServices(ctx context.Context, in *WatchServicesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SchemaRegistry_ServiceDesc.Streams[1], SchemaRegistry_WatchServices_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchServicesRequest, ServiceEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SchemaRegistry_WatchServicesClient = grpc.ServerStreamingClient[ServiceEvent]

// SchemaRegistryServer is the server API for SchemaRegistry service.
// All implementations must embed UnimplementedSchemaRegistryServer
// for forward compatibility.
type SchemaRegistryServer interface {
	// Schema Management
	CreateSchema(context.Context, *CreateSchemaRequest) (*SchemaResponse, error)
	GetSchema(context.Context, *GetSchemaRequest) (*SchemaResponse, error)
	UpdateSchema(context.Context, *UpdateSchemaRequest) (*SchemaResponse, error)
	DeleteSchema(context.Context, *DeleteSchemaRequest) (*DeleteSchemaResponse, error)
	ListSchemas(context.Context, *ListSchemasRequest) (*ListSchemasResponse, error)
	// Bundle Management
	CreateBundle(context.Context, *CreateBundleRequest) (*BundleResponse, error)
	GetBundle(context.Context, *GetBundleRequest) (*BundleResponse, error)
	ListBundles(context.Context, *ListBundlesRequest) (*ListBundlesResponse, error)
	// Service Registration
	RegisterService(context.Context, *RegisterServiceRequest) (*RegisterServiceResponse, error)
	DeregisterService(context.Context, *DeregisterServiceRequest) (*DeregisterServiceResponse, error)
	ServiceHeartbeat(context.Context, *ServiceHeartbeatRequest) (*ServiceHeartbeatResponse, error)
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	// Compatibility Testing
	CheckCompatibility(context.Context, *CheckCompatibilityRequest) (*CheckCompatibilityResponse, error)
	// Proto Compilation
	CompileProto(context.Context, *CompileProtoRequest) (*CompileProtoResponse, error)
	// Watch for changes
	WatchSchemas(*WatchSchemasRequest, grpc.ServerStreamingServer[SchemaEvent]) error
	WatchServices(*WatchServicesRequest, grpc.ServerStreamingServer[ServiceEvent]) error
	mustEmbedUnimplementedSchemaRegistryServer()
}

// UnimplementedSchemaRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchemaRegistryServer struct{}

func (UnimplementedSchemaRegistryServer) CreateSchema(context.Context, *CreateSchemaRequest) (*SchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSchema not implemented")
}
func (UnimplementedSchemaRegistryServer) GetSchema(context.Context, *GetSchemaRequest) (*SchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedSchemaRegistryServer) UpdateSchema(context.Context, *UpdateSchemaRequest) (*SchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSchema not implemented")
}
func (UnimplementedSchemaRegistryServer) DeleteSchema(context.Context, *DeleteSchemaRequest) (*DeleteSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSchema not implemented")
}
func (UnimplementedSchemaRegistryServer) ListSchemas(context.Context, *ListSchemasRequest) (*ListSchemasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSchemas not implemented")
}
func (UnimplementedSchemaRegistryServer) CreateBundle(context.Context, *CreateBundleRequest) (*BundleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBundle not implemented")
}
func (UnimplementedSchemaRegistryServer) GetBundle(context.Context, *GetBundleRequest) (*BundleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBundle not implemented")
}
func (UnimplementedSchemaRegistryServer) ListBundles(context.Context, *ListBundlesRequest) (*ListBundlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBundles not implemented")
}
func (UnimplementedSchemaRegistryServer) RegisterService(context.Context, *RegisterServiceRequest) (*RegisterServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterService not implemented")
}
func (UnimplementedSchemaRegistryServer) DeregisterService(context.Context, *DeregisterServiceRequest) (*DeregisterServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeregisterService not implemented")
}
func (UnimplementedSchemaRegistryServer) ServiceHeartbeat(context.Context, *ServiceHeartbeatRequest) (*ServiceHeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceHeartbeat not implemented")
}
func (UnimplementedSchemaRegistryServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedSchemaRegistryServer) CheckCompatibility(context.Context, *CheckCompatibilityRequest) (*CheckCompatibilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckCompatibility not implemented")
}
func (UnimplementedSchemaRegistryServer) CompileProto(context.Context, *CompileProtoRequest) (*CompileProtoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompileProto not implemented")
}
func (UnimplementedSchemaRegistryServer) WatchSchemas(*WatchSchemasRequest, grpc.ServerStreamingServer[SchemaEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchSchemas not implemented")
}
func (UnimplementedSchemaRegistryServer) WatchServices(*WatchServicesRequest, grpc.ServerStreamingServer[ServiceEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchServices not implemented")
}
func (UnimplementedSchemaRegistryServer) mustEmbedUnimplementedSchemaRegistryServer() {}
func (UnimplementedSchemaRegistryServer) testEmbeddedByValue()                        {}

// UnsafeSchemaRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchemaRegistryServer will
// result in compilation errors.
type UnsafeSchemaRegistryServer interface {
	mustEmbedUnimplementedSchemaRegistryServer()
}

func RegisterSchemaRegistryServer(s grpc.ServiceRegistrar, srv SchemaRegistryServer) {
	// If the following call pancis, it indicates UnimplementedSchemaRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchemaRegistry_ServiceDesc, srv)
}

func _SchemaRegistry_CreateSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaRegistryServer).CreateSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaRegistry_CreateSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaRegistryServer).CreateSchema(ctx, req.(*CreateSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaRegistry_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaRegistryServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaRegistry_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaRegistryServer).GetSchema(ctx, req.(*GetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaRegistry_UpdateSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaRegistryServer).UpdateSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaRegistry_UpdateSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaRegistryServer).UpdateSchema(ctx, req.(*UpdateSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaRegistry_DeleteSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaRegistryServer).DeleteSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaRegistry_DeleteSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaRegistryServer).DeleteSchema(ctx, req.(*DeleteSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaRegistry_ListSchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSchemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaRegistryServer).ListSchemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaRegistry_ListSchemas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaRegistryServer).ListSchemas(ctx, req.(*ListSchemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaRegistry_CreateBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaRegistryServer).CreateBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaRegistry_CreateBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaRegistryServer).CreateBundle(ctx, req.(*CreateBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaRegistry_GetBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaRegistryServer).GetBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaRegistry_GetBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaRegistryServer).GetBundle(ctx, req.(*GetBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaRegistry_ListBundles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBundlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaRegistryServer).ListBundles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaRegistry_ListBundles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaRegistryServer).ListBundles(ctx, req.(*ListBundlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaRegistry_RegisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaRegistryServer).RegisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaRegistry_RegisterService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaRegistryServer).RegisterService(ctx, req.(*RegisterServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaRegistry_DeregisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaRegistryServer).DeregisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaRegistry_DeregisterService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaRegistryServer).DeregisterService(ctx, req.(*DeregisterServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaRegistry_ServiceHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaRegistryServer).ServiceHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaRegistry_ServiceHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaRegistryServer).ServiceHeartbeat(ctx, req.(*ServiceHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaRegistry_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaRegistryServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaRegistry_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaRegistryServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaRegistry_CheckCompatibility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckCompatibilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaRegistryServer).CheckCompatibility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaRegistry_CheckCompatibility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaRegistryServer).CheckCompatibility(ctx, req.(*CheckCompatibilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaRegistry_CompileProto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompileProtoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaRegistryServer).CompileProto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaRegistry_CompileProto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaRegistryServer).CompileProto(ctx, req.(*CompileProtoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaRegistry_WatchSchemas_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchSchemasRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SchemaRegistryServer).WatchSchemas(m, &grpc.GenericServerStream[WatchSchemasRequest, SchemaEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SchemaRegistry_WatchSchemasServer = grpc.ServerStreamingServer[SchemaEvent]

func _SchemaRegistry_WatchServices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchServicesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SchemaRegistryServer).WatchServices(m, &grpc.GenericServerStream[WatchServicesRequest, ServiceEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SchemaRegistry_WatchServicesServer = grpc.ServerStreamingServer[ServiceEvent]

// SchemaRegistry_ServiceDesc is the grpc.ServiceDesc for SchemaRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchemaRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "schema.SchemaRegistry",
	HandlerType: (*SchemaRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSchema",
			Handler:    _SchemaRegistry_CreateSchema_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _SchemaRegistry_GetSchema_Handler,
		},
		{
			MethodName: "UpdateSchema",
			Handler:    _SchemaRegistry_UpdateSchema_Handler,
		},
		{
			MethodName: "DeleteSchema",
			Handler:    _SchemaRegistry_DeleteSchema_Handler,
		},
		{
			MethodName: "ListSchemas",
			Handler:    _SchemaRegistry_ListSchemas_Handler,
		},
		{
			MethodName: "CreateBundle",
			Handler:    _SchemaRegistry_CreateBundle_Handler,
		},
		{
			MethodName: "GetBundle",
			Handler:    _SchemaRegistry_GetBundle_Handler,
		},
		{
			MethodName: "ListBundles",
			Handler:    _SchemaRegistry_ListBundles_Handler,
		},
		{
			MethodName: "RegisterService",
			Handler:    _SchemaRegistry_RegisterService_Handler,
		},
		{
			MethodName: "DeregisterService",
			Handler:    _SchemaRegistry_DeregisterService_Handler,
		},
		{
			MethodName: "ServiceHeartbeat",
			Handler:    _SchemaRegistry_ServiceHeartbeat_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _SchemaRegistry_ListServices_Handler,
		},
		{
			MethodName: "CheckCompatibility",
			Handler:    _SchemaRegistry_CheckCompatibility_Handler,
		},
		{
			MethodName: "CompileProto",
			Handler:    _SchemaRegistry_CompileProto_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchSchemas",
			Handler:       _SchemaRegistry_WatchSchemas_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchServices",
			Handler:       _SchemaRegistry_WatchServices_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "schema_registry.proto",
}
