// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: aegis.proto

package aegispb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastVersion   string                 `protobuf:"bytes,1,opt,name=last_version,json=lastVersion,proto3" json:"last_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_aegis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_aegis_proto_rawDescGZIP(), []int{0}
}

func (x *SyncRequest) GetLastVersion() string {
	if x != nil {
		return x.LastVersion
	}
	return ""
}

type AuthDataEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*AuthDataEvent_UserRoles
	//	*AuthDataEvent_TokenRevoked
	//	*AuthDataEvent_SyncComplete
	Event         isAuthDataEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthDataEvent) Reset() {
	*x = AuthDataEvent{}
	mi := &file_aegis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthDataEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthDataEvent) ProtoMessage() {}

func (x *AuthDataEvent) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthDataEvent.ProtoReflect.Descriptor instead.
func (*AuthDataEvent) Descriptor() ([]byte, []int) {
	return file_aegis_proto_rawDescGZIP(), []int{1}
}

func (x *AuthDataEvent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AuthDataEvent) GetEvent() isAuthDataEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AuthDataEvent) GetUserRoles() *UserRolesSnapshot {
	if x != nil {
		if x, ok := x.Event.(*AuthDataEvent_UserRoles); ok {
			return x.UserRoles
		}
	}
	return nil
}

func (x *AuthDataEvent) GetTokenRevoked() *TokenRevoked {
	if x != nil {
		if x, ok := x.Event.(*AuthDataEvent_TokenRevoked); ok {
			return x.TokenRevoked
		}
	}
	return nil
}

func (x *AuthDataEvent) GetSyncComplete() *SyncComplete {
	if x != nil {
		if x, ok := x.Event.(*AuthDataEvent_SyncComplete); ok {
			return x.SyncComplete
		}
	}
	return nil
}

type isAuthDataEvent_Event interface {
	isAuthDataEvent_Event()
}

type AuthDataEvent_UserRoles struct {
	UserRoles *UserRolesSnapshot `protobuf:"bytes,2,opt,name=user_roles,json=userRoles,proto3,oneof"`
}

type AuthDataEvent_TokenRevoked struct {
	TokenRevoked *TokenRevoked `protobuf:"bytes,3,opt,name=token_revoked,json=tokenRevoked,proto3,oneof"`
}

type AuthDataEvent_SyncComplete struct {
	SyncComplete *SyncComplete `protobuf:"bytes,4,opt,name=sync_complete,json=syncComplete,proto3,oneof"`
}

func (*AuthDataEvent_UserRoles) isAuthDataEvent_Event() {}

func (*AuthDataEvent_TokenRevoked) isAuthDataEvent_Event() {}

func (*AuthDataEvent_SyncComplete) isAuthDataEvent_Event() {}

type UserRolesSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Permissions   []string               `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRolesSnapshot) Reset() {
	*x = UserRolesSnapshot{}
	mi := &file_aegis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRolesSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRolesSnapshot) ProtoMessage() {}

func (x *UserRolesSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRolesSnapshot.ProtoReflect.Descriptor instead.
func (*UserRolesSnapshot) Descriptor() ([]byte, []int) {
	return file_aegis_proto_rawDescGZIP(), []int{2}
}

func (x *UserRolesSnapshot) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRolesSnapshot) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UserRolesSnapshot) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *UserRolesSnapshot) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type TokenRevoked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jti           string                 `protobuf:"bytes,1,opt,name=jti,proto3" json:"jti,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRevoked) Reset() {
	*x = TokenRevoked{}
	mi := &file_aegis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRevoked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRevoked) ProtoMessage() {}

func (x *TokenRevoked) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRevoked.ProtoReflect.Descriptor instead.
func (*TokenRevoked) Descriptor() ([]byte, []int) {
	return file_aegis_proto_rawDescGZIP(), []int{3}
}

func (x *TokenRevoked) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

func (x *TokenRevoked) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type SyncComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncComplete) Reset() {
	*x = SyncComplete{}
	mi := &file_aegis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncComplete) ProtoMessage() {}

func (x *SyncComplete) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncComplete.ProtoReflect.Descriptor instead.
func (*SyncComplete) Descriptor() ([]byte, []int) {
	return file_aegis_proto_rawDescGZIP(), []int{4}
}

type PolicyEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Policies      map[string]string      `protobuf:"bytes,2,rep,name=policies,proto3" json:"policies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyEvent) Reset() {
	*x = PolicyEvent{}
	mi := &file_aegis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyEvent) ProtoMessage() {}

func (x *PolicyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyEvent.ProtoReflect.Descriptor instead.
func (*PolicyEvent) Descriptor() ([]byte, []int) {
	return file_aegis_proto_rawDescGZIP(), []int{5}
}

func (x *PolicyEvent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PolicyEvent) GetPolicies() map[string]string {
	if x != nil {
		return x.Policies
	}
	return nil
}

type CheckPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	ResourceType  string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId    string                 `protobuf:"bytes,4,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionRequest) Reset() {
	*x = CheckPermissionRequest{}
	mi := &file_aegis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRequest) ProtoMessage() {}

func (x *CheckPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return file_aegis_proto_rawDescGZIP(), []int{6}
}

func (x *CheckPermissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckPermissionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckPermissionRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *CheckPermissionRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CheckPermissionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type CheckPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionResponse) Reset() {
	*x = CheckPermissionResponse{}
	mi := &file_aegis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionResponse) ProtoMessage() {}

func (x *CheckPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionResponse) Descriptor() ([]byte, []int) {
	return file_aegis_proto_rawDescGZIP(), []int{7}
}

func (x *CheckPermissionResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckPermissionResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ValidateAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAPIKeyRequest) Reset() {
	*x = ValidateAPIKeyRequest{}
	mi := &file_aegis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAPIKeyRequest) ProtoMessage() {}

func (x *ValidateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*ValidateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_aegis_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateAPIKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type ValidateAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Scopes        []string               `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAPIKeyResponse) Reset() {
	*x = ValidateAPIKeyResponse{}
	mi := &file_aegis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAPIKeyResponse) ProtoMessage() {}

func (x *ValidateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*ValidateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_aegis_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateAPIKeyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateAPIKeyResponse) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ValidateAPIKeyResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ValidateAPIKeyResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

var File_aegis_proto protoreflect.FileDescriptor

const file_aegis_proto_rawDesc = "" +
	"\n" +
	"\vaegis.proto\x12\aaegispb\"0\n" +
	"\vSyncRequest\x12!\n" +
	"\flast_version\x18\x01 \x01(\tR\vlastVersion\"\xeb\x01\n" +
	"\rAuthDataEvent\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12;\n" +
	"\n" +
	"user_roles\x18\x02 \x01(\v2\x1a.aegispb.UserRolesSnapshotH\x00R\tuserRoles\x12<\n" +
	"\rtoken_revoked\x18\x03 \x01(\v2\x15.aegispb.TokenRevokedH\x00R\ftokenRevoked\x12<\n" +
	"\rsync_complete\x18\x04 \x01(\v2\x15.aegispb.SyncCompleteH\x00R\fsyncCompleteB\a\n" +
	"\x05event\"\x81\x01\n" +
	"\x11UserRolesSnapshot\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissions\"?\n" +
	"\fTokenRevoked\x12\x10\n" +
	"\x03jti\x18\x01 \x01(\tR\x03jti\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"\x0e\n" +
	"\fSyncComplete\"\xa4\x01\n" +
	"\vPolicyEvent\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12>\n" +
	"\bpolicies\x18\x02 \x03(\v2\".aegispb.PolicyEvent.PoliciesEntryR\bpolicies\x1a;\n" +
	"\rPoliciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x01\n" +
	"\x16CheckPermissionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x04 \x01(\tR\n" +
	"resourceId\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\"K\n" +
	"\x17CheckPermissionResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"0\n" +
	"\x15ValidateAPIKeyRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"~\n" +
	"\x16ValidateAPIKeyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes2\xb2\x02\n" +
	"\tAegisAuth\x12>\n" +
	"\fSyncAuthData\x12\x14.aegispb.SyncRequest\x1a\x16.aegispb.AuthDataEvent0\x01\x12<\n" +
	"\fSyncPolicies\x12\x14.aegispb.SyncRequest\x1a\x14.aegispb.PolicyEvent0\x01\x12T\n" +
	"\x0fCheckPermission\x12\x1f.aegispb.CheckPermissionRequest\x1a .aegispb.CheckPermissionResponse\x12Q\n" +
	"\x0eValidateAPIKey\x12\x1e.aegispb.ValidateAPIKeyRequest\x1a\x1f.aegispb.ValidateAPIKeyResponseB0Z.github.com/jasonKoogler/abraxis/aegis/api/grpc/aegispbb\x06proto3"

var (
	file_aegis_proto_rawDescOnce sync.Once
	file_aegis_proto_rawDescData []byte
)

func file_aegis_proto_rawDescGZIP() []byte {
	file_aegis_proto_rawDescOnce.Do(func() {
		file_aegis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aegis_proto_rawDesc), len(file_aegis_proto_rawDesc)))
	})
	return file_aegis_proto_rawDescData
}

var file_aegis_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_aegis_proto_goTypes = []any{
	(*SyncRequest)(nil),             // 0: aegispb.SyncRequest
	(*AuthDataEvent)(nil),           // 1: aegispb.AuthDataEvent
	(*UserRolesSnapshot)(nil),       // 2: aegispb.UserRolesSnapshot
	(*TokenRevoked)(nil),            // 3: aegispb.TokenRevoked
	(*SyncComplete)(nil),            // 4: aegispb.SyncComplete
	(*PolicyEvent)(nil),             // 5: aegispb.PolicyEvent
	(*CheckPermissionRequest)(nil),  // 6: aegispb.CheckPermissionRequest
	(*CheckPermissionResponse)(nil), // 7: aegispb.CheckPermissionResponse
	(*ValidateAPIKeyRequest)(nil),   // 8: aegispb.ValidateAPIKeyRequest
	(*ValidateAPIKeyResponse)(nil),  // 9: aegispb.ValidateAPIKeyResponse
	nil,                             // 10: aegispb.PolicyEvent.PoliciesEntry
}
var file_aegis_proto_depIdxs = []int32{
	2,  // 0: aegispb.AuthDataEvent.user_roles:type_name -> aegispb.UserRolesSnapshot
	3,  // 1: aegispb.AuthDataEvent.token_revoked:type_name -> aegispb.TokenRevoked
	4,  // 2: aegispb.AuthDataEvent.sync_complete:type_name -> aegispb.SyncComplete
	10, // 3: aegispb.PolicyEvent.policies:type_name -> aegispb.PolicyEvent.PoliciesEntry
	0,  // 4: aegispb.AegisAuth.SyncAuthData:input_type -> aegispb.SyncRequest
	0,  // 5: aegispb.AegisAuth.SyncPolicies:input_type -> aegispb.SyncRequest
	6,  // 6: aegispb.AegisAuth.CheckPermission:input_type -> aegispb.CheckPermissionRequest
	8,  // 7: aegispb.AegisAuth.ValidateAPIKey:input_type -> aegispb.ValidateAPIKeyRequest
	1,  // 8: aegispb.AegisAuth.SyncAuthData:output_type -> aegispb.AuthDataEvent
	5,  // 9: aegispb.AegisAuth.SyncPolicies:output_type -> aegispb.PolicyEvent
	7,  // 10: aegispb.AegisAuth.CheckPermission:output_type -> aegispb.CheckPermissionResponse
	9,  // 11: aegispb.AegisAuth.ValidateAPIKey:output_type -> aegispb.ValidateAPIKeyResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_aegis_proto_init() }
func file_aegis_proto_init() {
	if File_aegis_proto != nil {
		return
	}
	file_aegis_proto_msgTypes[1].OneofWrappers = []any{
		(*AuthDataEvent_UserRoles)(nil),
		(*AuthDataEvent_TokenRevoked)(nil),
		(*AuthDataEvent_SyncComplete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aegis_proto_rawDesc), len(file_aegis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aegis_proto_goTypes,
		DependencyIndexes: file_aegis_proto_depIdxs,
		MessageInfos:      file_aegis_proto_msgTypes,
	}.Build()
	File_aegis_proto = out.File
	file_aegis_proto_goTypes = nil
	file_aegis_proto_depIdxs = nil
}
