// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: aegis.proto

package aegispb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AegisAuth_SyncAuthData_FullMethodName    = "/aegispb.AegisAuth/SyncAuthData"
	AegisAuth_SyncPolicies_FullMethodName    = "/aegispb.AegisAuth/SyncPolicies"
	AegisAuth_CheckPermission_FullMethodName = "/aegispb.AegisAuth/CheckPermission"
	AegisAuth_ValidateAPIKey_FullMethodName  = "/aegispb.AegisAuth/ValidateAPIKey"
)

// AegisAuthClient is the client API for AegisAuth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AegisAuthClient interface {
	SyncAuthData(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AuthDataEvent], error)
	SyncPolicies(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PolicyEvent], error)
	CheckPermission(ctx context.Context, in *CheckPermissionRequest, opts ...grpc.CallOption) (*CheckPermissionResponse, error)
	ValidateAPIKey(ctx context.Context, in *ValidateAPIKeyRequest, opts ...grpc.CallOption) (*ValidateAPIKeyResponse, error)
}

type aegisAuthClient struct {
	cc grpc.ClientConnInterface
}

func NewAegisAuthClient(cc grpc.ClientConnInterface) AegisAuthClient {
	return &aegisAuthClient{cc}
}

func (c *aegisAuthClient) SyncAuthData(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AuthDataEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AegisAuth_ServiceDesc.Streams[0], AegisAuth_SyncAuthData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SyncRequest, AuthDataEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AegisAuth_SyncAuthDataClient = grpc.ServerStreamingClient[AuthDataEvent]

func (c *aegisAuthClient) SyncPolicies(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PolicyEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AegisAuth_ServiceDesc.Streams[1], AegisAuth_SyncPolicies_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SyncRequest, PolicyEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AegisAuth_SyncPoliciesClient = grpc.ServerStreamingClient[PolicyEvent]

func (c *aegisAuthClient) CheckPermission(ctx context.Context, in *CheckPermissionRequest, opts ...grpc.CallOption) (*CheckPermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPermissionResponse)
	err := c.cc.Invoke(ctx, AegisAuth_CheckPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisAuthClient) ValidateAPIKey(ctx context.Context, in *ValidateAPIKeyRequest, opts ...grpc.CallOption) (*ValidateAPIKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateAPIKeyResponse)
	err := c.cc.Invoke(ctx, AegisAuth_ValidateAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AegisAuthServer is the server API for AegisAuth service.
// All implementations must embed UnimplementedAegisAuthServer
// for forward compatibility.
type AegisAuthServer interface {
	SyncAuthData(*SyncRequest, grpc.ServerStreamingServer[AuthDataEvent]) error
	SyncPolicies(*SyncRequest, grpc.ServerStreamingServer[PolicyEvent]) error
	CheckPermission(context.Context, *CheckPermissionRequest) (*CheckPermissionResponse, error)
	ValidateAPIKey(context.Context, *ValidateAPIKeyRequest) (*ValidateAPIKeyResponse, error)
	mustEmbedUnimplementedAegisAuthServer()
}

// UnimplementedAegisAuthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAegisAuthServer struct{}

func (UnimplementedAegisAuthServer) SyncAuthData(*SyncRequest, grpc.ServerStreamingServer[AuthDataEvent]) error {
	return status.Error(codes.Unimplemented, "method SyncAuthData not implemented")
}
func (UnimplementedAegisAuthServer) SyncPolicies(*SyncRequest, grpc.ServerStreamingServer[PolicyEvent]) error {
	return status.Error(codes.Unimplemented, "method SyncPolicies not implemented")
}
func (UnimplementedAegisAuthServer) CheckPermission(context.Context, *CheckPermissionRequest) (*CheckPermissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPermission not implemented")
}
func (UnimplementedAegisAuthServer) ValidateAPIKey(context.Context, *ValidateAPIKeyRequest) (*ValidateAPIKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateAPIKey not implemented")
}
func (UnimplementedAegisAuthServer) mustEmbedUnimplementedAegisAuthServer() {}
func (UnimplementedAegisAuthServer) testEmbeddedByValue()                   {}

// UnsafeAegisAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AegisAuthServer will
// result in compilation errors.
type UnsafeAegisAuthServer interface {
	mustEmbedUnimplementedAegisAuthServer()
}

func RegisterAegisAuthServer(s grpc.ServiceRegistrar, srv AegisAuthServer) {
	// If the following call panics, it indicates UnimplementedAegisAuthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AegisAuth_ServiceDesc, srv)
}

func _AegisAuth_SyncAuthData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SyncRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AegisAuthServer).SyncAuthData(m, &grpc.GenericServerStream[SyncRequest, AuthDataEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AegisAuth_SyncAuthDataServer = grpc.ServerStreamingServer[AuthDataEvent]

func _AegisAuth_SyncPolicies_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SyncRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AegisAuthServer).SyncPolicies(m, &grpc.GenericServerStream[SyncRequest, PolicyEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AegisAuth_SyncPoliciesServer = grpc.ServerStreamingServer[PolicyEvent]

func _AegisAuth_CheckPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisAuthServer).CheckPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisAuth_CheckPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisAuthServer).CheckPermission(ctx, req.(*CheckPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisAuth_ValidateAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisAuthServer).ValidateAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisAuth_ValidateAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisAuthServer).ValidateAPIKey(ctx, req.(*ValidateAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AegisAuth_ServiceDesc is the grpc.ServiceDesc for AegisAuth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AegisAuth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aegispb.AegisAuth",
	HandlerType: (*AegisAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckPermission",
			Handler:    _AegisAuth_CheckPermission_Handler,
		},
		{
			MethodName: "ValidateAPIKey",
			Handler:    _AegisAuth_ValidateAPIKey_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncAuthData",
			Handler:       _AegisAuth_SyncAuthData_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SyncPolicies",
			Handler:       _AegisAuth_SyncPolicies_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "aegis.proto",
}
